language: rust
rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx
  - windows

jobs:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

before_script:
  # Install rustfmt
  - rustup component add rustfmt
  # Install clippy
  - rustup toolchain install nightly-2020-01-02-x86_64-unknown-linux-gnu
  - rustup component add clippy --toolchain nightly-2020-01-02-x86_64-unknown-linux-gnu

script:
  # Check formatting
  - rustfmt --edition=2018 src/lib.rs --check
  # Check clippy lints
  - cargo +nightly-2020-01-02 clippy
  # Run build and tests
  - cargo build --verbose --release
  - cargo test --verbose --release -- --nocapture
  # Generate documentation
  - cargo doc --verbose --release

notifications:
  email:
    on_success: change
    on_failure: always
